### ISSUE TITLE
Grade is NaN%

### ISSUE THREAD

**Issue by heyitswither** [Bertik750/ManagebacGradeCalculator#1]
Not sure what info would help, I can give more if needed.

Console output:

```
content.js:1 ready
content.js:7 Exists!
content.js:79 NaN
```

Could it have something to do with not having any grades for a category?

**Comment by Bertik750** [comment]
Hello, this happened when a grade was not a number. For example when the grade looks like this:  
[ - / 10 ] It is fixed now.
