### ISSUE TITLE
NaN%

### ISSUE THREAD

**Issue by Wubadao321** [Bertik750/ManagebacGradeCalculator#2]
Hi!
After a recent update of Managebac, the GradeChart just cannot show up(pic listed below), so the grade part shows NaN%. I presume it happens because the Managebac changes the structure of "Tasks" pages.

![image](https://user-images.githubusercontent.com/20981270/86379209-24c5b900-bcbd-11ea-999e-2c8d34b7096a.png)

PS: the console shows that 
```
NaN content.js:112 

Exists! pickColor.js:11 

test content.js:157

```

Thanks！

**Comment by Wubadao321** [comment]
I don't know why, but the problem seem doesn't appear anymore. LOL

**Comment by Bertik750** [comment]
Hey, thanks for the report! I was on holiday and managed to fix it in a rush. Managebac changed the way categories were placed and so I had to rewrite the code a little. Today I published a more refined version.
